### ISSUE TITLE
Selected radio button not preserved after POST

### ISSUE THREAD

**Issue by hprovyn** [hprovyn/str-to-haplogroup-predictor#3]
After selecting an STR format radio button and submitting data, the page reloads with default radio button selected

**Comment by tkrahn** [comment]
I suppose this needs a functional cookie (unless you want to implement a login procedure which I wouldn't recommend).

**Comment by hprovyn** [comment]
I think I can solve it through pure PHP checking radio state sent with the POST

**Comment by hprovyn** [comment]
resolved in commit b2598416cde6b7c7487db7a3aafcd0d10b0c858c
